### ISSUE TITLE
Negative IOU

### ISSUE THREAD

**Issue by titanbender** [experiencor/keras-yolo2#277]
After successfully training the object detector, which performs very well, I wanted to compare the overlap of my ground truth with the predicted boundary boxes. The IOU results of 426 examples were on average 0.9, which is very good. That said, there were 7 outliers of which some of them had a negative IOU. I was baffled to see this, as the overlap shouldn't be possible to be under 0. Any thoughts on how this could happen? Is it possible that the predicted YOLO boundary box width was negative and that messes up my calculations? Thanks for your time.

**Comment by rodrigo2019** [comment]
My guess is that in situations like this figure:

![image](https://user-images.githubusercontent.com/8016520/39719560-f5419060-520f-11e8-96f6-4d3da923d9ce.png)
 negative can occurs when the boxes are not connected at all.

Following this [example](https://www.pyimagesearch.com/2016/11/07/intersection-over-union-iou-for-object-detection/) you can check yourself that situations.

It already happened with me, but I'm just guessing, because I do not know how IOU works exactly in thi implementation

**Comment by titanbender** [comment]
Thanks @rodrigo2019 - that answered my question and what we wrong!
